[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bf_codegen"
version = "0.1.0"
description = ""
readme = ""
requires-python = ">=3.7"
classifiers = ["Programming Language :: Python :: 3"]
